### PR TITLE
allow redirect_uris with * at the end

### PR DESCRIPTION
**Pull request by adrai**

### CODE REVIEW

**Comment by christiansmith** [comment]
@adrai, thanks for the pull request. Can you clarify the purpose of these changes?

**Comment by adrai** [comment]
We want to implement pickup urls with invitation codes and need to authenticate when such an url is called. And to match invitation code to user we need to pass the invitation code in the redirect uri...



Il giorno 5-feb-2015, alle ore 23:52, Christian Smith <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@adrai<https://github.com/adrai>, thanks for the pull request. Can you clarify the purpose of these changes?

-

**Comment by christiansmith** [comment]
The reason I ask is that I'm reluctant to make any changes to the `redirect_uri` mechanism given the potential for introducing vulnerabilities. 

Knowing what you're trying to do, I would suggest a safer way might be to use the [state param](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) as a way of matching up an auth response to an invite code on the client side. You'd need to temporarily cache your invite code keyed by the `state` value generated by your client. 

It's really a good idea to take advantage of the state param anyways as a guard against [Cross-Site Request Forgery](https://tools.ietf.org/html/rfc6749#section-10.12)

You might be interested to know we're planning to build token-based invitations directly into Anvil Connect in the near future. If you have specific requirements for this we'd love to hear about them. I'm glad to make some time to pair program on this with you as well.

**Comment by adrai** [comment]
Sound interesting, I will try to look at it...

**Comment by adrai** [comment]
yes, I can confirm your advice did work ;-)
THANKS

**Comment by christiansmith** [comment]
Glad I could help, @adrai. 

We hold weekly Google hangouts for this project every Thursday, alternating between 9am and 2pm Pacific time. The next one is February 12th at 2pm.  If you'd like to join in, we'd love to hear about what you're working on and what you need from Anvil Connect. 

Email me for an invite: smith@anvil.io

**Pull request closed without merging**
